# Site settings
title: TTFAutohint
description: > # this means to ignore newlines until "baseurl:"
  Help Us Improve TTFAutohint
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
